model:
  type: moco
  base_encoder: resnet50
  moco_type: moco_superpixel_cluster_bioptimus  # Options: moco_v2, moco_superpixel, moco_superpixel_cluster, moco_superpixel_cluster_bioptimus
  output_dim: 128
  queue_size: 32768  #512
  num_clusters: 50
  momentum: 0.9
  temperature: 0.07
  init_queue_type: awared_random #options: random, awared_random

training:
  use_neighbors: True
  device: cuda:0
  batch_size: 256
  epochs: 100
  learning_rate: 0.003
  weight_decay: 1e-4
  optimizer: sgd
  alpha: 0.05
  beta: 0.01
  lambda_bml: 100
  warm_up_step: 100
  update_step: 50
  resume_checkpoint: false
  seed: 42
  num_workers: 16
  pin_memory: true
  prefetch_factor: 2

#paths:
 # output_base: reports/  # base output folder for all plots and reports

logging:
  log_interval: 10

cluster:
  cluster_type: cluster_bioptimus  # no_cluster, cluster_resnet, cluster_bioptimus, cluster_uni

loss:
  type: cluster # cluster, contrastive  
  alpha: 0.5