embeddings:
  type: bioptimus # Options: moco, resnet50, bioptimus, superpixel+cluster, superpixel
  dim: 2048 # Options: moco=128, resnet50=2048, bioptimus=1536, superpixel+cluster=128, superpixel=128


training:
  
  device: cuda:0
  batch_size: 4
  epochs: 2
  learning_rate: 0.001
  weight_decay: 1e-4
  optimizer: adam
  val_split: 0.25
  early_stopping: true
  early_stopping_patience: 10
  resume_checkpoint: false
  seed: 42
  num_workers: 16
  pin_memory: true
  prefetch_factor: 2

model:
  hidden_dim: 128
  attention_dim: 128
  attention_branches: 1
  num_classes: 3
  dropout: 0.25


logging:
  log_interval: 10



mil:
  mode: train  # Options: train, test
  label_mapping:
    LUAD: 0
    LSCC: 1
    Normal: 2

    
