embeddings:
  type: superpixel_cluster # Options: mocov2, resnet50, bioptimus, superpixel_cluster, superpixel
  dim: 2048 # Options: moco=128, resnet50=2048, bioptimus=1536, superpixel+cluster=128, superpixel=128
  projection_dim: 128
  projection: False


training:
  
  device: cuda:0
  batch_size: 4
  epochs: 1000
  learning_rate: 0.0005
  weight_decay: 1e-4
  optimizer: adam
  val_split: 0.15
  early_stopping: true
  early_stopping_patience: 20
  resume_checkpoint: false
  seed: 42
  num_workers: 16
  pin_memory: true
  prefetch_factor: 2
  bag: None

model:
  hidden_dim: 256 #go bigger 512
  attention_dim: 128 #256
  attention_branches: 1
  num_classes: 3
  dropout: 0.4


logging:
  log_interval: 10



mil:
  mode: train  # Options: train, test
  label_mapping:
    LUAD: 0
    LSCC: 1
    Normal: 2

    
